### index handler

GET http://localhost:8080/

### update handler
PATCH http://localhost:8080/
Content-Type: application/json

{
  "skills": ["Rust", "Go", "TypeScript"]
}

### invalid request

PATCH http://localhost:8081/
Content-Type: application/json

{
  "skills": ["Rust"]
}


### url shortener
POST http://localhost:8080/
Content-Type: application/json

{
  "url": "https://www.rust-lang.org/"
}

### url redirect
GET http://localhost:8080/iH1c7h
